@startuml
robust "CLK" as CLK
concise "Signals" as SIG
robust "ENA" as ENA
robust "RST_N" as RST_N
robust "UI_IN" as UI_IN
robust "UIO" as UIO
robust "UO_OUT" as UO_OUT

ENA is {undef}
RST_N is {undef}
UI_IN is {undef}
UIO is {undef}
UO_OUT is {undef}

@ 0
SIG is "Reset"
ENA is High
RST_N is Low
UI_IN is "0x0"
UIO is "0x0"
@ 0
CLK is High
@ 0.5
CLK is Low

@ 1
SIG is "Cycle 0 (IDLE)"
ENA is High
RST_N is High
UI_IN is "0x0"
UIO is "0x0"
@ 1
CLK is High
@ 1.5
CLK is Low

@ 2
SIG is "Cycle 1 (Load Scale A & Config)"
UI_IN is "0x7f"
UIO is "0x0"
@ 2
CLK is High
@ 2.5
CLK is Low

@ 3
SIG is "Cycle 2 (Load Scale B & Format B)"
UI_IN is "0x7f"
UIO is "0x0"
@ 3
CLK is High
@ 3.5
CLK is Low

@ 4
SIG is "Cycles 3-34 (Stream 32 elements) (trunc)"
UI_IN is "0x38"
UIO is "0x38"
@ 4
CLK is High
@ 4.5
CLK is Low
@ 5
CLK is High
@ 5.5
CLK is Low

@ 6
SIG is "Cycle 35 (Pipeline Flush)"
UI_IN is "0x0"
UIO is "0x0"
@ 6
CLK is High
@ 6.5
CLK is Low

@ 7
SIG is "Cycle 36 (Final Shared Scaling)"
UI_IN is "0x0"
UIO is "0x0"
@ 7
CLK is High
@ 7.5
CLK is Low

@ 8
SIG is "Cycle 37 (Read Result Byte 3)"
UO_OUT is "Result[31:24]"
@ 8
CLK is High
@ 8.5
CLK is Low
@ 9
@enduml