@startuml
robust "CLK" as CLK
concise "Phase" as SIG
binary "ENA" as ENA
binary "RST_N" as RST_N
concise "UI_IN" as UI_IN
concise "UIO" as UIO
concise "UO_OUT" as UO_OUT

@0
CLK is Low
SIG is {-}
ENA is 0
RST_N is 0
UI_IN is 0
UIO is 0
UO_OUT is 0

@0
SIG is Reset
ENA is 1
RST_N is 0
UI_IN is 0
UIO is 0
@0
CLK is High
@0.5
CLK is Low

@1
SIG is Cycle_0_IDLE
ENA is 1
RST_N is 1
UI_IN is 0
UIO is 0
@1
CLK is High
@1.5
CLK is Low

@2
SIG is Cycle_1_Load_Scale_A__Config
UI_IN is 127
UIO is 0
@2
CLK is High
@2.5
CLK is Low

@3
SIG is Cycle_2_Load_Scale_B__Format_B
UI_IN is 127
UIO is 0
@3
CLK is High
@3.5
CLK is Low

@4
SIG is Cycles_3-34_Stream_32_elements
UI_IN is 56
UIO is 56
@4
CLK is High
@4.5
CLK is Low
@5
CLK is High
@5.5
CLK is Low
@6
CLK is High
@6.5
CLK is Low
@7
CLK is High
@7.5
CLK is Low
@8
CLK is High
@8.5
CLK is Low
@9
CLK is High
@9.5
CLK is Low
@10
CLK is High
@10.5
CLK is Low
@11
CLK is High
@11.5
CLK is Low
@12
CLK is High
@12.5
CLK is Low
@13
CLK is High
@13.5
CLK is Low
@14
CLK is High
@14.5
CLK is Low
@15
CLK is High
@15.5
CLK is Low
@16
CLK is High
@16.5
CLK is Low
@17
CLK is High
@17.5
CLK is Low
@18
CLK is High
@18.5
CLK is Low
@19
CLK is High
@19.5
CLK is Low
@20
CLK is High
@20.5
CLK is Low
@21
CLK is High
@21.5
CLK is Low
@22
CLK is High
@22.5
CLK is Low
@23
CLK is High
@23.5
CLK is Low
@24
CLK is High
@24.5
CLK is Low
@25
CLK is High
@25.5
CLK is Low
@26
CLK is High
@26.5
CLK is Low
@27
CLK is High
@27.5
CLK is Low
@28
CLK is High
@28.5
CLK is Low
@29
CLK is High
@29.5
CLK is Low
@30
CLK is High
@30.5
CLK is Low
@31
CLK is High
@31.5
CLK is Low
@32
CLK is High
@32.5
CLK is Low
@33
CLK is High
@33.5
CLK is Low
@34
CLK is High
@34.5
CLK is Low
@35
CLK is High
@35.5
CLK is Low

@36
SIG is Cycle_35_Pipeline_Flush
UI_IN is 0
UIO is 0
@36
CLK is High
@36.5
CLK is Low

@37
SIG is Cycle_36_Final_Shared_Scaling
UI_IN is 0
UIO is 0
@37
CLK is High
@37.5
CLK is Low

@38
SIG is Cycle_37_Read_Result_Byte_3
UO_OUT is "Result[31:24]"
@38
CLK is High
@38.5
CLK is Low

@39
SIG is Cycle_38_Read_Result_Byte_2
UO_OUT is "Result[23:16]"
@39
CLK is High
@39.5
CLK is Low

@40
SIG is Cycle_39_Read_Result_Byte_1
UO_OUT is "Result[15:8]"
@40
CLK is High
@40.5
CLK is Low

@41
SIG is Cycle_40_Read_Result_Byte_0
UO_OUT is "Result[7:0]"
@41
CLK is High
@41.5
CLK is Low
@enduml