@startuml
robust "CLK" as CLK
concise "Phase" as SIG
binary "RST_N" as RST_N
concise "UO_OUT" as UO_OUT

@0
CLK is Low
SIG is {-}
RST_N is 0
UO_OUT is 0

@0
SIG is "Reset"
RST_N is 0
UO_OUT is "???"
@0
CLK is High
@0.5
CLK is Low

@1
SIG is "Count_1"
RST_N is 1
UO_OUT is 1
@1
CLK is High
@1.5
CLK is Low

@2
SIG is "Count_2"
RST_N is 1
UO_OUT is 2
@2
CLK is High
@2.5
CLK is Low

@3
SIG is "Count_3"
RST_N is 1
UO_OUT is 3
@3
CLK is High
@3.5
CLK is Low

@4
SIG is "Count_4"
RST_N is 1
UO_OUT is 4
@4
CLK is High
@4.5
CLK is Low
@enduml