@startuml
robust "CLK" as CLK
concise "Phase" as SIG
concise "UO_OUT" as UO_OUT

@0
CLK is Low
SIG is {-}
UO_OUT is 0

@0
SIG is "Initial_Reset"
UO_OUT is 0
@0
CLK is High
@0.5
CLK is Low

@1
SIG is "Initial_Count_States"
UO_OUT is 0
@1
CLK is High
@1.5
CLK is Low
@2
CLK is High
@2.5
CLK is Low
@3
CLK is High
@3.5
CLK is Low
@4
CLK is High
@4.5
CLK is Low
@enduml