@startuml
robust "CLK" as CLK
concise "Phase" as SIG
concise "A" as A
concise "B" as B
concise "Sum" as Sum

@0
CLK is Low
SIG is {-}
A is 0
B is 0
Sum is 0

@0
SIG is 0_+_0_=_0
A is 0
B is 0
Sum is 0
@0
CLK is High
@0.5
CLK is Low

@1
SIG is 1_+_1_=_2
A is 1
B is 1
Sum is 2
@1
CLK is High
@1.5
CLK is Low

@2
SIG is 15_+_1_=_16
A is 15
B is 1
Sum is 16
@2
CLK is High
@2.5
CLK is Low

@3
SIG is 15_+_15_=_30
A is 15
B is 15
Sum is 30
@3
CLK is High
@3.5
CLK is Low

@4
SIG is 5_+_10_=_15
A is 5
B is 10
Sum is 15
@4
CLK is High
@4.5
CLK is Low
@enduml